// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYfv7w41kZUAGdwlUUGppkzupKLNrYV-Y',
    appId: '1:476715547262:web:f0b2a6f6c893d9c6c4f62f',
    messagingSenderId: '476715547262',
    projectId: 'shoppiewell',
    authDomain: 'shoppiewell.firebaseapp.com',
    storageBucket: 'shoppiewell.firebasestorage.app',
    measurementId: 'G-FE0Y5DYQS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEG_bf80U1EhKOvFyTGllBGyjFyBSJGr8',
    appId: '1:476715547262:android:46bc0490e2368e29c4f62f',
    messagingSenderId: '476715547262',
    projectId: 'shoppiewell',
    storageBucket: 'shoppiewell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0zKP-m2FkIIH_fZ_CPVsNyhlWqhWn1Y',
    appId: '1:476715547262:ios:d6ebb01fffc44365c4f62f',
    messagingSenderId: '476715547262',
    projectId: 'shoppiewell',
    storageBucket: 'shoppiewell.firebasestorage.app',
    iosBundleId: 'com.example.shoppieWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK0zKP-m2FkIIH_fZ_CPVsNyhlWqhWn1Y',
    appId: '1:476715547262:ios:d6ebb01fffc44365c4f62f',
    messagingSenderId: '476715547262',
    projectId: 'shoppiewell',
    storageBucket: 'shoppiewell.firebasestorage.app',
    iosBundleId: 'com.example.shoppieWell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYfv7w41kZUAGdwlUUGppkzupKLNrYV-Y',
    appId: '1:476715547262:web:4a43a4eca3430e3ec4f62f',
    messagingSenderId: '476715547262',
    projectId: 'shoppiewell',
    authDomain: 'shoppiewell.firebaseapp.com',
    storageBucket: 'shoppiewell.firebasestorage.app',
    measurementId: 'G-YQ8JXXK41J',
  );
}
